// ============================================================================
// TAILWIND CSS CONFIGURATION
// ============================================================================

tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "on-background": "#e0e3e1",
        "outline-variant": "#3c4a42",
        "surface-card-hover": "rgba(20, 36, 29, 0.8)",
        "surface-variant": "#313634",
        secondary: "#95d3ba",
        "on-primary": "#003824",
        "primary-container": "#10b981",
        "tertiary-fixed-dim": "#45dfa4",
        "surface-container-high": "#272b2a",
        "border-glass-glow": "rgba(16, 185, 129, 0.45)",
        "gender-female": "#F472B6",
        "surface-container": "#1c201f",
        "gender-male": "#38BDF8",
        error: "#ffb4ab",
        "on-tertiary": "#003825",
        "surface-dim": "#101413",
        "surface-container-lowest": "#0b0f0e",
        "text-primary": "#F9FAFB",
        "on-secondary-container": "#83c2a9",
        "border-glass": "rgba(52, 211, 153, 0.15)",
        "surface-container-highest": "#313634",
        "text-secondary": "#9CA3AF",
        "surface-dark": "#070B0A",
        "on-primary-fixed-variant": "#005236",
        background: "#101413",
        "on-secondary-fixed-variant": "#0b513d",
        "surface-bright": "#363a39",
        "on-surface-variant": "#bbcabf",
        "on-primary-container": "#00422b",
        "error-container": "#93000a",
        "primary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#005137",
        "on-tertiary-fixed": "#002114",
        "on-surface": "#e0e3e1",
        "secondary-container": "#0b513d",
        "on-error": "#690005",
        "on-secondary": "#003829",
        "secondary-fixed": "#b0f0d6",
        "surface-container-low": "#181c1b",
        primary: "#4edea3",
        surface: "#101413",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#00422c",
        "surface-tint": "#4edea3",
        "inverse-primary": "#006c49",
        "inverse-surface": "#e0e3e1",
        "tertiary-container": "#00b982",
        "inverse-on-surface": "#2d3130",
        "text-muted": "#4B5563",
        outline: "#86948a",
        "accent-neon": "#00FF87",
        "surface-card": "rgba(13, 22, 18, 0.65)",
        "on-secondary-fixed": "#002117",
        tertiary: "#45dfa4",
        "tertiary-fixed": "#68fcbf",
        "on-primary-fixed": "#002113",
        "secondary-fixed-dim": "#95d3ba",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-md": "1rem",
        "gutter-sm": "0.5rem",
        "gutter-xl": "2rem",
        "gutter-lg": "1.5rem",
        "container-max": "1200px",
        "section-sm": "3rem",
        "gutter-xs": "0.25rem",
        "section-lg": "6rem",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans"],
        "label-lg": ["Manrope"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-sm": ["Manrope"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "display-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        display: [
          "56px",
          {
            lineHeight: "64px",
            letterSpacing: "-0.03em",
            fontWeight: "800",
          },
        ],
        "label-lg": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.04em",
            fontWeight: "600",
          },
        ],
        "body-lg": [
          "16px",
          {
            lineHeight: "24px",
            fontWeight: "400",
          },
        ],
        "body-md": [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "400",
          },
        ],
        "label-sm": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.08em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg-mobile": [
          "26px",
          {
            lineHeight: "34px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "headline-sm": [
          "18px",
          {
            lineHeight: "26px",
            fontWeight: "600",
          },
        ],
        "display-mobile": [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "headline-md": [
          "22px",
          {
            lineHeight: "30px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
      },
    },
  },
};

// ============================================================================
// STUDENT DATA
// ============================================================================

const STUDENTS_DATA = {
  male: [
    "Faalih Arkaan",
    "Muhammad Alfindra Auvar Rehardja",
    "Handanu Indrafaza Styawan",
    "Almer Abrisam Dzaky Noor",
    "Muhammad Hafidz Setiadi",
    "Muhammad Zharif Syatir",
    "Cheerul Risyed Ferdiansyah",
    "Hafidz Alfatih Hermanto",
    "Muhammad Atha Alieudin Hamani",
    "Muhammad Azka Alieudin Kalani",
    "Muhammad Asyraf Al Farisi",
    "Ahmad Faeyza Rafa",
    "Ahmad Abdullah Hafi Munaji",
    "Muhammad El Junot Razqal",
    "Al Ghazali Fahran",
    "Muhammad Faqih Ramadhan",
    "Muhammad Abdurrahman Dzaki",
    "Alkhalifi Hasyimi",
    "Lathief Akmal El Azzam",
    "Rega Rahmad Afandi",
    "Azka Aisy Muhammad Firdaus",
    "Muhammad Ragil Ardah Putra",
    "Giovanny Syahputra",
    "Hasan Ahmad",
    "Asbillah Saunna",
    "Ba'Ats Nurfu'Ad Wetiman",
    "Fattah Altaf Qusyairi",
    "Namara Simaloan Athariz Nasution",
    "Farrel Azka Firlana",
    "Albuchori Amrullah Syarif",
    "Super Novel Hardian",
    "Muhammad Naufal",
    "Rafay Messi",
    "Devan Rafandra Pratama",
    "Abdullah Dzaky Editya",
    "Jeevan Fhaeyza Daniswara",
    "Rayhan Aqilla Akmal Triono",
  ],
  female: [
    "Adzkira Rindu Edelweiss",
    "Annisa Wafa Luthfi",
    "Putri Meilisha",
    "Nada Fajriah Salsabilla",
    "Asghia Khaureen Nazhifa Arianto",
    "Alesha Zevanna Anneyla Alfian",
    "Alisha Nur Afiyah",
    "Alenka Shafeea Akbari",
    "Khalilah Tsamara Azizah",
    "Dzakira Talita Nur Asy",
    "Felisha Rafalya Chafid",
    "Shidqia Nabila Azzahra",
    "Arini Syaurah Zayani",
    "Ainun Miftahul Aggenia",
    "Fatimah Az-Zahra",
    "Aisyah Afiqah Wahyudi",
    "Vanisha Malditya Chafid",
    "Ameera Aqeela Sadli",
    "Amirah Ramadhani Zainal",
    "Sachi Siddiqia Tomo",
    "Zahratu Syifa",
    "Afiqah Abidah Urfa",
    "Shazia Amira Zhafirah",
    "Nur Aisyah",
    "Adinda Nur Annisa",
    "Shybilya Sheren",
    "Adelia Felicia",
    "Angelina Natalia Tennes",
    "Nabila Widya Prajna",
    "Zara Qisya Ramadhani",
    "Aqilah Khayyirah",
    "Nadhifa Wihda Syauqia",
    "Syaquila Marwa Putri Deandra",
    "Kanaya Lubna Janitra Hafizah",
    "Alisya Zella Naura Saputro",
    "Kimberly Wong",
    "Afika Aulia Izza Tunnisa'",
    "Afiqah Humayra Arresky",
    "Deeandra Mikhailla Hariyadi",
    "Hanania Hasanah Mukti",
    "Lathifah Azizah Ali",
    "Nurul Farhana Aqilah Chandra",
  ],
};
